# Generated by Django 4.0 on 2021-12-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customer_information_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_information',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
